warning_threshold: 5

disabled_rules:
  - unused_setter_value
  - trailing_whitespace
  - comment_spacing
  - function_body_length
  - cyclomatic_complexity
  - compiler_protocol_init
  - todo
  - identifier_name
  - block_based_kvo
  - empty_enum_arguments
  - unused_enumerated
  - empty_count
  
# temporary disabled
  - for_where
  - multiple_closures_with_trailing_closure
  - force_try
  
opt_in_rules: # some rules are only opt-in
  - unused_declaration
  - explicit_self

included: # paths to include during linting
    - UnsplashAppTask

disabled_rules:
- trailing_whitespace

opt_in_rules:
- empty_count
- empty_string

excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib

line_length:
    warning: 150
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
    
function_body_length:
    warning: 300
    error: 500
    
function_parameter_count:
    warning: 6
    error: 8
    
type_body_length:
    warning: 300
    error: 500
    
force_try:
  severity: warning
    
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
    
cyclomatic_complexity:
    warning: 15
    error: 25
    
reporter: "xcode"
